### ISSUE TITLE
1

### ISSUE THREAD

**Issue by catch-moonlight** [moxiu2012/PJ_NLP#1]
求上传

**Comment by moxiu2012** [comment]
> 求上传
从这里下载中文词向量
https://github.com/Embedding/Chinese-Word-Vectors

**Comment by catch-moonlight** [comment]
> 
> 
> > 求上传
> > 从这里下载中文词向量
> > https://github.com/Embedding/Chinese-Word-Vectors

请问具体是哪一个呢 有很多 谢谢您

**Comment by moxiu2012** [comment]
我当时使用的是综合类的（Mixed-large 综合 Word + Character + Ngram） 你可以自己选择 
不过这个词向量是文本类型的，我这里先把它转为矩阵形式了。你可以直接使用文本读入进行一行行解析，也可以使用gensim读入。如
from gensim.models.keyedvectors import KeyedVectors
model = KeyedVectors.load_word2vec_format(emb_file, binary=False)
那么矩阵就是model.vectors, 词汇就是model.index2word了

**Comment by catch-moonlight** [comment]
> 
> 
> 我当时使用的是综合类的（Mixed-large 综合 Word + Character + Ngram） 你可以自己选择
> 不过这个词向量是文本类型的，我这里先把它转为矩阵形式了。你可以直接使用文本读入进行一行行解析，也可以使用gensim读入。如
> from gensim.models.keyedvectors import KeyedVectors
> model = KeyedVectors.load_word2vec_format(emb_file, binary=False)
> 那么矩阵就是model.vectors, 词汇就是model.index2word了
好的，非常感谢您

**Comment by catch-moonlight** [comment]
好的，非常感谢您，鞠躬〈（_　_）〉
